# Generated by Django 3.2.8 on 2021-12-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lgin',
        ),
    ]
