# Generated by Django 3.2.8 on 2021-12-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_lgin'),
    ]

    operations = [
        migrations.CreateModel(
            name='lgin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('lgpassword', models.CharField(max_length=8)),
                ('fname', models.CharField(max_length=10)),
                ('snmae', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('crpassword', models.CharField(max_length=8)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
    ]
