# Generated by Django 3.2.8 on 2021-12-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_lgin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgin',
            name='lgpassword',
        ),
        migrations.RemoveField(
            model_name='lgin',
            name='username',
        ),
    ]
