# Generated by Django 3.2.8 on 2021-12-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211210_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgin',
            old_name='snmae',
            new_name='sname',
        ),
    ]
