# Generated by Django 3.2.8 on 2021-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_snmae_lgin_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgin',
            name='dateofbirth',
            field=models.CharField(max_length=20),
        ),
    ]
