# Generated by Django 3.2.8 on 2021-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_lgin_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgin',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
